config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :clients, controllers: { sessions: 'clients/sessions'}

  resources :cards

  resources :branches do
    resources :bankers
  end

  resources :clients do
    resources :accounts
  end

  resources :users

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :account
  belongs_to :status
  belongs_to :type

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:PAN, :expiryDate, :limit, :managingCompany, :account_id, :status_id, :type_id)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :PAN %><br>
    <%= f.text_field :PAN %>
  </div>
  <div class="field">
    <%= f.label :expiryDate %><br>
    <%= f.date_select :expiryDate %>
  </div>
  <div class="field">
    <%= f.label :limit %><br>
    <%= f.text_field :limit %>
  </div>
  <div class="field">
    <%= f.label :managingCompany %><br>
    <%= f.text_field :managingCompany %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br>
    <%= f.text_field :status_id %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.number_field :type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cards</h1>

<table>
  <thead>
    <tr>
      <th>Pan</th>
      <th>Expirydate</th>
      <th>Limit</th>
      <th>Managingcompany</th>
      <th>Account</th>
      <th>Status</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.PAN %></td>
        <td><%= card.expiryDate %></td>
        <td><%= card.limit %></td>
        <td><%= card.managingCompany %></td>
        <td><%= card.account_id %></td>
        <td><%= card.status_id %></td>
        <td><%= card.type_id %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pan:</strong>
  <%= @card.PAN %>
</p>

<p>
  <strong>Expirydate:</strong>
  <%= @card.expiryDate %>
</p>

<p>
  <strong>Limit:</strong>
  <%= @card.limit %>
</p>

<p>
  <strong>Managingcompany:</strong>
  <%= @card.managingCompany %>
</p>

<p>
  <strong>Account:</strong>
  <%= @card.account_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @card.status_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @card.type_id %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>