config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :clients, controllers: { sessions: 'clients/sessions'}

  resources :cards

  resources :branches do
    resources :bankers
  end

  resources :clients do
    resources :accounts
  end

  resources :users

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :status
  belongs_to :category
  belongs_to :client
  has_one :card
  validates :beginDate, :expiryDate, :saldo, :rate, presence: true

end

app/models/banker.rb
class Banker < ActiveRecord::Base
  has_many :clients
  belongs_to :branch
  validates :name, :street, :streetNr, :zipCode, :city, presence: true

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :bankers
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :account
  belongs_to :status
  belongs_to :type

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :accounts
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :banker
  has_many :accounts
  validates :lastName, :street, :streetNr, :zipCode, :city, :birthDate, :birthPlace, :socialSecurityNumber, presence: true
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :accounts
  has_many :cards

end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :cards

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/bankers_controller.rb
class BankersController < ApplicationController
  before_action :set_banker, only: [:show, :edit, :update, :destroy]

  # GET /bankers
  # GET /bankers.json
  def index
    @bankers = Banker.all
  end

  # GET /bankers/1
  # GET /bankers/1.json
  def show
  end

  # GET /bankers/new
  def new
    @banker = Banker.new
  end

  # GET /bankers/1/edit
  def edit
  end

  # POST /bankers
  # POST /bankers.json
  def create
    @banker = Banker.new(banker_params)

    respond_to do |format|
      if @banker.save
        format.html { redirect_to @banker, notice: 'Banker was successfully created.' }
        format.json { render :show, status: :created, location: @banker }
      else
        format.html { render :new }
        format.json { render json: @banker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bankers/1
  # PATCH/PUT /bankers/1.json
  def update
    respond_to do |format|
      if @banker.update(banker_params)
        format.html { redirect_to @banker, notice: 'Banker was successfully updated.' }
        format.json { render :show, status: :ok, location: @banker }
      else
        format.html { render :edit }
        format.json { render json: @banker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bankers/1
  # DELETE /bankers/1.json
  def destroy
    @banker.destroy
    respond_to do |format|
      format.html { redirect_to bankers_url, notice: 'Banker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banker
      @banker = Banker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banker_params
      params.require(:banker).permit(:firstName, :lastName, :mobileNumber, :phoneNumber, :email, :branch_id)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:PAN, :expiryDate, :limit, :managingCompany, :account_id, :status_id, :type_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bankers_helper.rb
module BankersHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>Online Bank</title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>


  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>

  <![endif]-->
</head>

<body>
<div class="container">
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>

<header class="navbar navbar-fixed-top navbar-inverse">
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Online Banking</a>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li class="active"><a href="/agencies">Agencies</a></li>
          <li class="active"><a href="/dashboard">Dashboard</a></li>
          <% if client_signed_in? %>
              <li class="active"><a href="/accounts">Products</a></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if client_signed_in? %>
              Logged in as <strong><%= current_client.firstName %></strong> <strong><%= current_client.lastName %></strong>.
              <%= link_to 'Edit profile', edit_client_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_client_session_path, method: :delete, :class => 'navbar-link'  %>

          <% else %>
              <span class="glyphicon glyphicon-user"></span><%= link_to "Become Client", new_client_registration_path, :class => 'navbar-link'  %>  |
              <span class="glyphicon glyphicon-user"></span><%= link_to "Login", new_client_session_path, :class => 'navbar-link'  %>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
</header>



<div class="container">
  <%= yield %>
</div>

</body>

<footer>
  <div class="container">
    Author: Mohamed El Aazioui
  </div>
</footer>
</html>