config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :clients, controllers: { sessions: 'clients/sessions'}

  resources :cards

  resources :branches do
    resources :bankers
  end

  resources :clients do
    resources :accounts
  end

  resources :users

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :status
  belongs_to :category
  belongs_to :client
  has_one :card
  validates :beginDate, :expiryDate, :saldo, :rate, presence: true

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:beginDate, :expiryDate, :saldo, :rate, :client_id, :status_id, :category_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :beginDate %><br>
    <%= f.date_select :beginDate %>
  </div>
  <div class="field">
    <%= f.label :expiryDate %><br>
    <%= f.date_select :expiryDate %>
  </div>
  <div class="field">
    <%= f.label :saldo %><br>
    <%= f.text_field :saldo %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br>
    <%= f.number_field :status_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Begindate</th>
      <th>Expirydate</th>
      <th>Saldo</th>
      <th>Rate</th>
      <th>Client</th>
      <th>Status</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.beginDate %></td>
        <td><%= account.expiryDate %></td>
        <td><%= account.saldo %></td>
        <td><%= account.rate %></td>
        <td><%= account.client_id %></td>
        <td><%= account.status_id %></td>
        <td><%= account.category_id %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Begindate:</strong>
  <%= @account.beginDate %>
</p>

<p>
  <strong>Expirydate:</strong>
  <%= @account.expiryDate %>
</p>

<p>
  <strong>Saldo:</strong>
  <%= @account.saldo %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @account.rate %>
</p>

<p>
  <strong>Client:</strong>
  <%= @account.client_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @account.status_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @account.category_id %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>